name: empty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4

flutter:
  assets:
    - assets/dado_1.svg
    - assets/dado_2.svg
    - assets/dado_3.svg
    - assets/dado_4.svg
    - assets/dado_5.svg
    - assets/dado_6.svg
